version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: "transaction_db"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    container_name: postgres
    ports:
      - '6500:5432'
    volumes:
      - progresDB:/data/postgres
    env_file:
      - ./.env
volumes:
  progresDB: